/* automatically generated by rust-bindgen 0.60.1 */

extern "C" {
    pub fn test1(name: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn adder(lhs: ::std::os::raw::c_int, rhs: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
